.TH mmake 1 "26 September 2026" "Version 1.0"

.SH NAME
mmake - my make, small simple version of Make

.SH SYNOPSIS
mmake [-f MMAKEFILE] [-B] [-s] [TARGET ...]

.SH DESCRIPTION
TODO

.SH OPTIONS
TODO

.SH SOLUTION
TODO

.SH EXIT STATUS
.IP 0
    TODO
.IP 1
    TODO

.SH AUTHORS
Aleksander Zdunek <redacted>@cs.umu.se

This program was an assignment for the course Systemnära Programmering 5DV254 at UMU.
